services:
  - type: web
    name: crew-ai-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: crew_server.py

  - type: web
    name: crew-ai-frontend
    env: node
    buildCommand: cd crew-dashboard && npm install && npm run build
    startCommand: cd crew-dashboard && npm start
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: REACT_APP_API_URL
        value: https://crew-ai-backend.onrender.com 